apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs-app
    author: ritika-singh
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
  # For cloud providers, you can use LoadBalancer type:
  # type: LoadBalancer